services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres1:5432/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HTTP_PORT: 8080
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8090:8080"
    depends_on:
      - postgres1
      - postgres2
    command:
      - "start-dev"
      - "--features=admin-fine-grained-authz,token-exchange"
    restart: unless-stopped
    networks:
      - keycloak-network

  postgres1:
    image: postgres:15
    container_name: postgres1
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
      POSTGRES_DB: keycloak
    networks:
      - keycloak-network

  postgres2:
    image: postgres:15
    container_name: postgres2
    restart: always
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
      POSTGRES_DB: keycloak
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge